version: '3.8'

services:
  pasa-commercial-app:
    build: .
    image: pasa-commercial-app:latest
    container_name: pasa-commercial-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8165:80"
